templateDir: Templates
files:
  extension-api.mustache:
    templateType: API
    destinationFilename: +Deferred.swift
additionalProperties:
  readonlyProperties: true
  lenientTypeCast: true
  responseAs: Combine