//
// NewsAPI+Deferred.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(Combine)
import Combine
#endif

#if canImport(Combine)
extension NewsAPI {
    /**

     - parameter apiToken: (query)  
     - parameter limit: (query)  
     - parameter page: (query)  
     - parameter search: (query)  (optional)
     - parameter language: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<InlineResponse200, Error>
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deferred_newsAllGet(apiToken: String, limit: Int, page: Int, search: String? = nil, language: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue) -> AnyPublisher<InlineResponse200, Error> {
        return Deferred {
            newsAllGet(apiToken: apiToken, limit: limit, page: page, search: search, language: language,  apiResponseQueue: apiResponseQueue)
        }
        .eraseToAnyPublisher()
    }

    /**

     - parameter apiToken: (query)  
     - parameter uuid: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<NewsInfo, Error>
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deferred_newsByUUIDGet(apiToken: String, uuid: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue) -> AnyPublisher<NewsInfo, Error> {
        return Deferred {
            newsByUUIDGet(apiToken: apiToken, uuid: uuid,  apiResponseQueue: apiResponseQueue)
        }
        .eraseToAnyPublisher()
    }

}
#endif
