//
// Meta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Meta: Codable, JSONEncodable, Hashable {

    public private(set) var found: Int
    public private(set) var returned: Int
    public private(set) var limit: Int
    public private(set) var page: Int

    public init(found: Int, returned: Int, limit: Int, page: Int) {
        self.found = found
        self.returned = returned
        self.limit = limit
        self.page = page
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case found
        case returned
        case limit
        case page
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(found, forKey: .found)
        try container.encode(returned, forKey: .returned)
        try container.encode(limit, forKey: .limit)
        try container.encode(page, forKey: .page)
    }
}

